from groq import Groq


PROMPT_TEMPLATE = """You are a senior procurement specialist AI assistant.

A procurement manager has requested your analysis. Below is scored vendor data generated by an automated scoring system:

{vendor_data}

Additional context from the procurement team:
{context}

Please provide:

1. **Primary Recommendation** — Which vendor to select and the top 3 reasons why.
2. **Risk Assessment** — Key risks with the recommended vendor and how to mitigate them.
3. **Backup Vendor** — Which vendor to fall back on and why.
4. **Negotiation Tips** — 2-3 specific negotiation points to improve the deal with the primary vendor.
5. **Red Flags** — Any vendors to avoid and why.

Keep your tone professional, specific, and actionable. Avoid generic advice.
"""


def get_recommendation(vendor_summary: str, context: str, api_key: str) -> str:
    client = Groq(api_key=api_key)

    prompt = PROMPT_TEMPLATE.format(
        vendor_data=vendor_summary,
        context=context if context.strip() else "No additional context provided.",
    )

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.3,
        max_tokens=900,
    )

    return response.choices[0].message.content